on:
  # Only triggered manually for pre-release.
  workflow_dispatch:

permissions: read-all

jobs:
  build:
    permissions:
      id-token: write # For signing.
      contents: write # For asset uploads.
      actions: read # For the entrypoint.
    # Update this line: the repo name and the reference
    # uses: ianlewis/slsa-github-generator/.github/workflows/builder_go_slsa3.yml@v1.8.0-rc.2
    uses: laurentsimon/slsa-github-generator/.github/workflows/builder_go_slsa3.yml@v1.9.0-rc.0
    with:
      go-version: "1.21"
      config-file: .github/configs-go/config-noldflags.yml

  if-succeeded:
    runs-on: ubuntu-latest
    needs: [build]
    if: needs.build.result == 'success'
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - run: |
          set -euo pipefail

          echo "This test should fail"
          exit 1
