name: Build using github-actions-demo
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: bazelisk build //:hello
      - uses: slsa-framework/github-actions-demo@v0.1
        with:
          artifact_path: bazel-bin/hello_/hello
          output_path: hello.provenance
        continue-on-error: true
      - uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
        with:
          path: |
            bazel-bin/hello_/hello
            hello.provenance
