name: shellcheck

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  # Needed to check out the repo.
  contents: read

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - env:
          SHELLCHECK_VERSION: "0.8.0"
        run: |
          set -euo pipefail

          # Install shellcheck
          wget -qO- "https://github.com/koalaman/shellcheck/releases/download/v${SHELLCHECK_VERSION}/shellcheck-v${SHELLCHECK_VERSION}.linux.x86_64.tar.xz" | tar -xJf -
          mv "shellcheck-v$SHELLCHECK_VERSION/shellcheck" /usr/local/bin

          # Run shellcheck and output github actions commands.
          # See: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions
          make shellcheck
